### ISSUE TITLE
Error running create_PyMC3_testmodels.py

### ISSUE THREAD

**Issue by asver12** [lumen-org/modelbase#65]
With pymc version 3.7 this error occurs:
```
Traceback (most recent call last):
  File "/home/schm_li/.local/lib/python3.6/site-packages/pymc3/theanof.py", line 65, in floatX
    return X.astype(theano.config.floatX)
AttributeError: 'list' object has no attribute 'astype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/schm_li/Documents/git/modelbase/mb_modelbase/models_core/tests/create_PyMC3_testmodels.py", line 369, in <module>
    data, m = func(fit=False)
  File "/home/schm_li/Documents/git/modelbase/mb_modelbase/models_core/tests/create_PyMC3_testmodels.py", line 214, in create_pymc3_eight_schools_model
    sd=standard_errors, observed=data['test_scores'])
  File "/home/schm_li/.local/lib/python3.6/site-packages/pymc3/distributions/distribution.py", line 45, in __new__
    dist = cls.dist(*args, **kwargs)
  File "/home/schm_li/.local/lib/python3.6/site-packages/pymc3/distributions/distribution.py", line 56, in dist
    dist.__init__(*args, **kwargs)
  File "/home/schm_li/.local/lib/python3.6/site-packages/pymc3/distributions/continuous.py", line 469, in __init__
    self.mean = self.median = self.mode = self.mu = mu = tt.as_tensor_variable(floatX(mu))
  File "/home/schm_li/.local/lib/python3.6/site-packages/pymc3/theanof.py", line 68, in floatX
    return np.asarray(X, dtype=theano.config.floatX)
  File "/home/schm_li/.local/lib/python3.6/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
```

**Comment by jong42** [comment]
The error does not occur with pymc3 version 3.5

**Comment by jong42** [comment]
I couldn't reproduce the error, even with pymc3 version 3.7. Which script did you run when you got the error?
