### ISSUE TITLE
KDE model class cannot deal with equal values

### ISSUE THREAD

**Issue by jong42** [lumen-org/modelbase#74]
The scipy.stats.gaussian_kde object cannot deal with inputs that have all equal values (for example the input [1,1,1,1]). The following error is thrown:
```
Traceback (most recent call last):
  File "/home/guet_jn/Desktop/modelbase/mb_modelbase/models_core/kde_model.py", line 257, in <module>
    kde_model._maximum()
  File "/home/guet_jn/Desktop/modelbase/mb_modelbase/models_core/kde_model.py", line 174, in _maximum
    local_max = sciopt.minimize(m._negdensity, x0, method='nelder-mead', options={'xtol': 1e-8, 'disp': False})
  File "/home/guet_jn/anaconda3/envs/modelbase_issue65/lib/python3.7/site-packages/scipy/optimize/_minimize.py", line 588, in minimize
    return _minimize_neldermead(fun, x0, args, callback, **options)
  File "/home/guet_jn/anaconda3/envs/modelbase_issue65/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 585, in _minimize_neldermead
    fsim[k] = func(sim[k])
  File "/home/guet_jn/anaconda3/envs/modelbase_issue65/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 326, in function_wrapper
    return function(*(wrapper_args + args))
  File "/home/guet_jn/Desktop/modelbase/mb_modelbase/models_core/kde_model.py", line 133, in _negdensity
    return -self._density(x)
  File "/home/guet_jn/Desktop/modelbase/mb_modelbase/models_core/kde_model.py", line 121, in _density
    kde = stats.gaussian_kde(cond_data.iloc[:, num_idx].T)
  File "/home/guet_jn/anaconda3/envs/modelbase_issue65/lib/python3.7/site-packages/scipy/stats/kde.py", line 208, in __init__
    self.set_bandwidth(bw_method=bw_method)
  File "/home/guet_jn/anaconda3/envs/modelbase_issue65/lib/python3.7/site-packages/scipy/stats/kde.py", line 554, in set_bandwidth
    self._compute_covariance()
  File "/home/guet_jn/anaconda3/envs/modelbase_issue65/lib/python3.7/site-packages/scipy/stats/kde.py", line 566, in _compute_covariance
    self._data_inv_cov = linalg.inv(self._data_covariance)
  File "/home/guet_jn/anaconda3/envs/modelbase_issue65/lib/python3.7/site-packages/scipy/linalg/basic.py", line 974, in inv
    raise LinAlgError("singular matrix")
numpy.linalg.LinAlgError: singular matrix
```

**Comment by jong42** [comment]
This somehow occurs when activating the data-local prediction facet.
